### ISSUE TITLE
Not able to understand how to train

### ISSUE THREAD

**Issue by MemeGamer** [Mquinn960/offline-trainer#15]
Hello,
i am college student from india. I am not able to understand the offline trainer instruction for example what does open up the load the project on intellij and run it ??

what to run which file and what is the configuration in the ide to run it which file.
please help if possible, if you can otherwise you can upload the train.xml file of 1 gb on mega.nz or google drive.

**Comment by Mquinn960** [comment]
Hello there,

If you'd like a pre-trained example SVM output, see this link:

https://drive.google.com/file/d/12qacJUjiKk5l_TmHY-olxb72GG3Je7CI/view?usp=drivesdk

Be aware that this was trained on my data, and will be less accurate than one you train yourself.

All the best!
Matt

**Comment by MemeGamer** [comment]
I used this XML file  to run the app, but it didn't give me good results ,
I was asking if you could give the big trained XML file or a explain what
file to run in intellij

Thank you for responding

Regards
Varun VP

**Comment by Mquinn960** [comment]
Hello,

It won't give good results, because it hasn't been trained on your own data -

You'll need to first create a large enough dataset that you can train the SVM correctly, for instructions on how to do this, please see https://github.com/Mquinn960/sign-language-help

If there's something that's unclear in this README please let me know and I can clarify

Cheers,
Matt
